spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/aggregator?currentSchema=aggregator_manager

aggregator:
  dictionary:
    url: http://hasura:8080/v1/graphql
  communicator:
    url: http://communicator:8080/graphql

kafka:
  bootstrapServers: kafka1:9092
