spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/aggregator?currentSchema=article_manager

aggregator:
  storage:
    url: http://data-storage:8080
  dictionary:
    url: http://hasura:8080/v1/graphql

kafka:
  bootstrapServers: kafka1:9092
