spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5434/aggregator?currentSchema=article_manager

aggregator:
  storage:
    url: http://data-storage:8080
  dictionary:
    url: http://hasura:8080/v1/graphql
