spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/aggregator?currentSchema=communicator

aggregator:
  dictionary:
    url: http://hasura:8080/v1/graphql

kafka:
  bootstrapServers: kafka1:9092
